Vagrant.configure("2") do |config|

  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
	web01.vm.network "private_network", ip: "192.168.40.11"
	web01.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = 2
   end
	web01.vm.provision "shell", inline: <<-SHELL
	apt update
	apt install apache2 wget unzip -y
	systemctl start apache2
	 systemctl enble apache2
	 cd /tmp/
	 wget https://www.tooplate.com/zip-templates/2129_crispy_kitchen.zip
	 unzip -o 2129_crispy_kitchen.zip
	 cp -r 2129_crispy_kitchen/* /var/www/html/
	 systemctl restart httpd
   SHELL
  end

  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"
	db01.vm.network "private_network", ip: "192.168.40.12"
	db01.vn.synced_folder "../devopsdata", "/vagrant_data"
	db01.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = 2
  end
  db01.vm.provision "shell", inline: <<-SHELL
   yum install mariadb-server -y
   systemctl start mariadb
   
	mysql -u root -e 'CREATE DATABASE wordpress;'
	mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost IDENTIFIED BY "admin123";'
	mysql -u root -e 'FLUSH PRIVILEGES;'
	SHELL
end
end